### ISSUE TITLE
[Week2] 대시보드 화면 개발, 로그인 기능 추가

### ISSUE THREAD

**Issue by roseline124** [roseline124/dreambody#11]
## Todos
1. 화면 개발
- [ ] summary 대시보드 - 섭취량, 소비량, 잔여칼로리 / 탄수화물, 단백질, 지방 @mye0ngs00 
- [ ] 물 추적기, 신체 정보(몸무게) @roseline124 
  - [x] 물 추적기 화면
  - [ ] 신체 정보

2. 기능 추가
- [x] 로그인 기능 @roseline124 

## +
- [ ] linter 추가 https://pub.dev/packages/linter
- [ ] widget 테스트 추가
- [x] 3번째 질문 화면 - 이미지 안뜨는 오류 해결
- [ ] statefulWidget에 props 전달하는 코드 제거
