### ISSUE TITLE
[Week3] 클라, API 연결

### ISSUE THREAD

**Issue by roseline124** [roseline124/dreambody#15]
## Todos
- [x] graphql client 추가 @roseline124 
- [ ] API로 폼에서 받은 정보 db에 저장 @mye0ngs00 
- [x] 로그인 연결 @roseline124 (week2)
