### ISSUE TITLE
[Week4]대시보드, 식사 기록 기능, 화면 추가 (본격적으로 API와 연동해봅시다 🔥)

### ISSUE THREAD

**Issue by roseline124** [roseline124/dreambody#19]
### Todos
1. 영양 화면(식사 기록) @roseline124  
- [x] 영양 화면 개발
- [x] 검색(백엔드 식품 영양 API 사용): 식사(아침, 점심, 저녁) 추가하기
  - [x] 검색 결과 버튼 리스트로 보여주기 
  - [x] 선택 시 식사 정보 저장 후 검색 결과 초기화
- [x] 아침, 점심, 저녁 먹은 칼로리 조회
- [x] 저장, 조회: 회원 식사 정보 (저장 시 데이터 실시간 업데이트)
- [x] 조회: 일일 영양소(summary) 정보
- [x] 저장, 조회: 물 정보
- [x] 물 정보 없을 때 조회하면 발생하는 에러 처리
- [x] 질문 대답 여부 따라 화면 라우팅

2. 요약 화면(대시보드) @mye0ngs00 
- [x] 회원 초기 입력 정보 저장(목표, 키, 몸무게 등)
- [x] 대시보드 화면 개발
- [x] 영양 정보랑 연동해서 칼로리, 탄단지 비율 보여주기

### Plus
- [x] 환경변수 사용
- [x] graphql -> flutter_graphql 패키지로 변경
~~[ ] test 코드 추가~~
