### ISSUE TITLE
[Week1] 화면 개발 - 질문 화면

### ISSUE THREAD

**Issue by roseline124** [roseline124/dreambody#4]
## Todos
- 세번째 화면 - 질문 화면
- [x] 현재 체중
- [x] 목표 체중
- [x] 성별
- [x] 키
- [x] 생일
- [x] 평소 나의 활동성 선택하기
    - 주로 좌식 생활을 하는 사람: BMR x 1.2
    - 약간 활동적인 사람 (주당 1일~3일 운동): BMR x 1.3
    - 보통 (주당 3일~5일 이상 운동): BMR x 1.5
    - 상당히 활동적인 사람 (매일 운동): BMR x 1.7
    - 매우 활동적(운동선수와 비슷한 강도로 매일 운동): BMR x 1.9

## Refactor
- [x] MaterialApp에 router 추가
- [x] selector 눌렀을 때 선택자가 맨 아래에 뜨는 문제 해결
- [x] 같은 레이아웃의 위젯은 공통 레이아웃 만들어서 사용

**Comment by roseline124** [comment]
아직 안끝났어요 ㅠㅠ close하지 말아주세요
